### ISSUE TITLE
glucoseAbnormal.fhir

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/loinc2hpo#138]
I do not think the following is valid FHIR because the LOINC test is quantitative and but the interpretation is "Abnormal" (which could be high or low).

https://github.com/monarch-initiative/loinc2hpo/blob/develop/loinc2hpo-fhir/src/test/resources/json/glucoseAbnormal.fhir

In principle, we could annotate this with Abnormal blood glucose concentration HP:0011015
But I am not sure this is valid FHIR? @kingmanzhang @iimpulse

**Comment by kingmanzhang** [comment]
It is a corner case that I can confirm it happens in real world but rarely. I see it as a "valid" FHIR as it will occur if the source data used "abnormal" instead of "high" or "low". Whether we want to include it as a demo case or not is not a critical decision in my mind, so either decision seems reasonable to me.

**Comment by pnrobinson** [comment]
fixed -- we should probably not allow invalid data to pass through unnoticed.
