### ISSUE TITLE
cannot annotate terms right now

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/loinc2hpo#71]
Hi @kingmanzhang - the LOINC app is not working at the moment, it won't pull up any HPO terms, I getting this error - see screenshot. I think JP was saying he was having similar issues the other day.

![image](https://user-images.githubusercontent.com/6722114/40257785-56fec632-5aa4-11e8-8f6e-4728db01ebeb.png)

**Comment by kingmanzhang** [comment]
This error message is intended to report a different one. JP's problem was that he was using a outdated hpo that does not have all the terms in the annotation file (solution: always pull most recent hpo and run "make"). This message pops up when the built-in function cannot find terms that contain the key words (so it's expected to happen at the right time). A few possibilities here:
1. if you double clicked on "Amphetamines[Presence]..." or clicked on "Auto Query", this is the expected outcome because current hpo does not have any term that has "amphetamines" in label or definition.
2. if you typed in "cardiac biomarker" and clicked "Manual Query", the app should be able to find one single HPO: 0500020. 
3. finally, you could check your configuration settings to see whether your hpo.owl setting is set to the intended file. 

I need a little more info to tell.
